services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --poll 2000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: api.settings
    depends_on:
      - redis
      - rabbitmq
    command: daphne -b 0.0.0.0 -p 8000 api.asgi:application

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: api.settings
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
    depends_on:
      - redis
      - rabbitmq
    command: celery -A api worker --loglevel=info --pool=threads