# Generated by Django 5.2 on 2025-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='status',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
